import type {
  Announcement,
  AttendanceCorrectionRequest,
  AttendancePeriodRecord,
  AuditLog,
  Branch,
  Department,
  DemoUser,
  DisciplinaryRecord,
  Employee,
  Holiday,
  LeaveRequest,
  LeaveType,
  OvertimeRequest,
  PayrollPeriod,
  PerformanceEvaluation,
  Position,
  WorkSchedule,
} from "./types";

// Fixed "today" so the demo's relative dates (birthdays, payroll periods, etc.)
// stay meaningful without depending on wall-clock time.
export const TODAY = "2026-07-13";

function addDays(dateStr: string, days: number): string {
  const d = new Date(dateStr + "T00:00:00Z");
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}

export function daysBetween(from: string, to: string): number {
  const a = new Date(from + "T00:00:00Z").getTime();
  const b = new Date(to + "T00:00:00Z").getTime();
  return Math.round((b - a) / 86400000);
}

// deterministic pseudo-random for cosmetic jitter (evaluation scores) only
function mulberry32(seed: number) {
  let a = seed;
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rng = mulberry32(20260713);

export const BRANCHES: Branch[] = [
  { id: "br-cbt", name: "Cabanatuan", code: "CBT", address: "Maharlika Highway, Cabanatuan City" },
  { id: "br-mnl", name: "Manila", code: "MNL", address: "Shantahl Bldg, Ortigas Ave, Pasig City" },
  { id: "br-ceb", name: "Cebu", code: "CEB", address: "IT Park, Cebu City" },
  { id: "br-mdu", name: "Mandaue", code: "MDU", address: "A.S. Fortuna St, Mandaue City" },
  { id: "br-dvo", name: "Davao", code: "DVO", address: "J.P. Laurel Ave, Davao City" },
  { id: "br-cav", name: "Cavite", code: "CAV", address: "Aguinaldo Highway, Cavite City" },
  { id: "br-cdo", name: "Cagayan de Oro", code: "CDO", address: "Corrales Ave, Cagayan de Oro" },
  { id: "br-pgs", name: "Pangasinan", code: "PGS", address: "McArthur Highway, Dagupan City, Pangasinan" },
  { id: "br-lcn", name: "Lucena", code: "LCN", address: "Merchan St, Lucena City" },
  { id: "br-bcd", name: "Bacolod", code: "BCD", address: "Lacson St, Bacolod City" },
];

export const DEPARTMENTS: Department[] = [
  { id: "dp-bod", name: "BOD" },
  { id: "dp-acctg", name: "Accounting" },
  { id: "dp-fin", name: "Finance" },
  { id: "dp-hr", name: "Human Resources" },
  { id: "dp-darofy-mktg", name: "Darofy - Marketing" },
  { id: "dp-darofy-sales", name: "Darofy - Sales" },
  { id: "dp-mlm-netdev", name: "MLM - Network Development" },
  { id: "dp-mlm-mktg", name: "MLM - Marketing" },
  { id: "dp-mlm-sales", name: "MLM - Sales" },
  { id: "dp-cosmetics", name: "Cosmetics" },
  { id: "dp-darofy-marketing-corp", name: "Darofy Marketing" },
  { id: "dp-indie-mktg", name: "Independent Marketing" },
  { id: "dp-operation", name: "Operations" },
];

export const POSITIONS: Position[] = [
  { id: "ps-chairman-of-the-board-1", title: "Chairman of the Board", departmentId: "dp-bod" },
  { id: "ps-president-for-cosmetics-2", title: "President for Cosmetics", departmentId: "dp-bod" },
  { id: "ps-president-for-darofy-3", title: "President for Darofy", departmentId: "dp-bod" },
  { id: "ps-vice-chairperson-4", title: "Vice Chairperson", departmentId: "dp-bod" },
  { id: "ps-chief-finance-officer-5", title: "Chief Finance Officer", departmentId: "dp-acctg" },
  { id: "ps-accounting-clerk-6", title: "Accounting Clerk", departmentId: "dp-acctg" },
  { id: "ps-sr-accounting-assistant-7", title: "Sr. Accounting Assistant", departmentId: "dp-acctg" },
  { id: "ps-jr-accounting-assistant-8", title: "Jr. Accounting Assistant", departmentId: "dp-acctg" },
  { id: "ps-bookkeeper-9", title: "Bookkeeper", departmentId: "dp-fin" },
  { id: "ps-corporate-treasurer-10", title: "Corporate Treasurer", departmentId: "dp-fin" },
  { id: "ps-hr-manager-11", title: "HR Manager", departmentId: "dp-hr" },
  { id: "ps-content-creator-12", title: "Content Creator", departmentId: "dp-darofy-mktg" },
  { id: "ps-marketing-head-13", title: "Marketing Head", departmentId: "dp-darofy-mktg" },
  { id: "ps-multimedia-artist-14", title: "Multimedia Artist", departmentId: "dp-darofy-mktg" },
  { id: "ps-sales-manager-15", title: "Sales Manager", departmentId: "dp-darofy-sales" },
  { id: "ps-sales-admin-16", title: "Sales Admin", departmentId: "dp-darofy-sales" },
  { id: "ps-network-development-head-luzon-17", title: "Network Development Head - Luzon", departmentId: "dp-mlm-netdev" },
  { id: "ps-network-development-head-visayas-18", title: "Network Development Head - Visayas", departmentId: "dp-mlm-netdev" },
  { id: "ps-network-development-head-mindanao-19", title: "Network Development Head - Mindanao", departmentId: "dp-mlm-netdev" },
  { id: "ps-multimedia-artist-20", title: "Multimedia Artist", departmentId: "dp-mlm-mktg" },
  { id: "ps-social-media-manager-21", title: "Social Media Manager", departmentId: "dp-mlm-mktg" },
  { id: "ps-video-editor-22", title: "Video Editor", departmentId: "dp-mlm-mktg" },
  { id: "ps-ads-specialist-23", title: "Ads Specialist", departmentId: "dp-mlm-sales" },
  { id: "ps-sales-admin-24", title: "Sales Admin", departmentId: "dp-mlm-sales" },
  { id: "ps-platform-specialist-25", title: "Platform Specialist", departmentId: "dp-cosmetics" },
  { id: "ps-multimedia-artist-head-26", title: "Multimedia Artist Head", departmentId: "dp-cosmetics" },
  { id: "ps-video-editor-27", title: "Video Editor", departmentId: "dp-cosmetics" },
  { id: "ps-multimedia-artist-head-mlm-28", title: "Multimedia Artist Head (MLM)", departmentId: "dp-darofy-marketing-corp" },
  { id: "ps-multimedia-artist-head-29", title: "Multimedia Artist Head", departmentId: "dp-mlm-mktg" },
  { id: "ps-marketing-assistant-30", title: "Marketing Assistant", departmentId: "dp-indie-mktg" },
  { id: "ps-product-specialist-31", title: "Product Specialist", departmentId: "dp-indie-mktg" },
  { id: "ps-cashier-32", title: "Cashier", departmentId: "dp-operation" },
  { id: "ps-csr-33", title: "CSR", departmentId: "dp-operation" },
  { id: "ps-warehouseman-34", title: "Warehouseman", departmentId: "dp-operation" },
  { id: "ps-operations-manager-35", title: "Operations Manager", departmentId: "dp-operation" },
  { id: "ps-driver-messenger-36", title: "Driver / Messenger", departmentId: "dp-operation" },
  { id: "ps-logistics-staff-37", title: "Logistics Staff", departmentId: "dp-operation" },
  { id: "ps-operations-supervisor-38", title: "Operations Supervisor", departmentId: "dp-operation" },
  { id: "ps-utility-39", title: "Utility", departmentId: "dp-operation" },
  { id: "ps-branch-supervisor-40", title: "Branch Supervisor", departmentId: "dp-operation" },
  { id: "ps-branch-manager-41", title: "Branch Manager", departmentId: "dp-operation" },
  { id: "ps-driver-warehouseman-42", title: "Driver / Warehouseman", departmentId: "dp-operation" },
  { id: "ps-stockman-43", title: "Stockman", departmentId: "dp-operation" },
];

export const WORK_SCHEDULES: WorkSchedule[] = [
  { id: "ws-day", name: "Day Shift", timeIn: "08:00", timeOut: "17:00", days: "Mon–Fri", graceMinutes: 10 },
  { id: "ws-early", name: "Early Shift", timeIn: "06:00", timeOut: "15:00", days: "Mon–Sat", graceMinutes: 10 },
  { id: "ws-mid", name: "Mid Shift", timeIn: "10:00", timeOut: "19:00", days: "Mon–Sat", graceMinutes: 10 },
  { id: "ws-night", name: "Night Shift", timeIn: "22:00", timeOut: "07:00", days: "Mon–Sat", graceMinutes: 15 },
  { id: "ws-flexi", name: "Flexi", timeIn: "09:00", timeOut: "18:00", days: "Mon–Fri", graceMinutes: 15 },
];

export const HOLIDAYS: Holiday[] = [
  { id: "hd-1", name: "New Year's Day", date: "2026-01-01", type: "regular", verified: true },
  { id: "hd-2", name: "Araw ng Kagitingan", date: "2026-04-09", type: "regular", verified: true },
  { id: "hd-3", name: "Maundy Thursday", date: "2026-04-02", type: "regular", verified: false },
  { id: "hd-4", name: "Good Friday", date: "2026-04-03", type: "regular", verified: false },
  { id: "hd-5", name: "Labor Day", date: "2026-05-01", type: "regular", verified: true },
  { id: "hd-6", name: "Independence Day", date: "2026-06-12", type: "regular", verified: true },
  { id: "hd-7", name: "Ninoy Aquino Day", date: "2026-08-21", type: "special_non_working", verified: true },
  { id: "hd-8", name: "National Heroes Day", date: "2026-08-31", type: "regular", verified: false },
  { id: "hd-9", name: "All Saints' Day (observed)", date: "2026-11-01", type: "special_non_working", verified: false },
  { id: "hd-10", name: "Bonifacio Day", date: "2026-11-30", type: "regular", verified: true },
  { id: "hd-11", name: "Christmas Day", date: "2026-12-25", type: "regular", verified: true },
  { id: "hd-12", name: "Rizal Day", date: "2026-12-30", type: "regular", verified: true },
  { id: "hd-13", name: "Last Day of the Year", date: "2026-12-31", type: "special_non_working", verified: false },
];

export const LEAVE_TYPES: LeaveType[] = [
  { id: "lt-vl", name: "Vacation Leave", defaultCredits: 15, requiresCert: false },
  { id: "lt-sl", name: "Sick Leave", defaultCredits: 15, requiresCert: true },
  { id: "lt-el", name: "Emergency Leave", defaultCredits: 3, requiresCert: false },
  { id: "lt-spl", name: "Solo Parent Leave", defaultCredits: 7, requiresCert: false },
  { id: "lt-ml", name: "Maternity Leave", defaultCredits: 105, requiresCert: true },
  { id: "lt-pl", name: "Paternity Leave", defaultCredits: 7, requiresCert: false },
  { id: "lt-bl", name: "Bereavement Leave", defaultCredits: 3, requiresCert: false },
  { id: "lt-lwop", name: "Leave Without Pay", defaultCredits: 0, requiresCert: false },
];

export const PAYROLL_PERIODS: PayrollPeriod[] = [
  { id: "pp-1", start: "2026-05-01", end: "2026-05-15", status: "closed" },
  { id: "pp-2", start: "2026-05-16", end: "2026-05-31", status: "closed" },
  { id: "pp-3", start: "2026-06-01", end: "2026-06-15", status: "closed" },
  { id: "pp-4", start: "2026-06-16", end: "2026-06-30", status: "closed" },
  { id: "pp-5", start: "2026-07-01", end: "2026-07-15", status: "locked" },
  { id: "pp-6", start: "2026-07-16", end: "2026-07-31", status: "open" },
];

// Real employee roster imported from the company's Excel 201-file export
// (BRANCH / DEPARTMENT / DIVISION / Position / Salary / Allowance columns).
// Fields not present in that export (birthdate, contact info, government-ID
// seeds, etc.) are deterministically generated placeholders — see the
// per-employee "illustrative" convention used throughout this demo.
let empSeq = 0;
function nextEmployeeNumber(): string {
  empSeq += 1;
  return `SDSI-${String(empSeq).padStart(4, "0")}`;
}

export const EMPLOYEES: Employee[] = [
  {
    id: "emp-001", employeeNumber: nextEmployeeNumber(),
    firstName: "Lowel", lastName: "Magdadaro", nickname: "Lowe",
    gender: "Female", birthdate: "1975-01-03", civilStatus: "Single", nationality: "Filipino",
    address: "819 Mabini St., CBT", contactNumber: "09814377841", email: "lowel.magdadaro@shantahl.com.ph",
    emergencyContactName: "Santos, Emergency Contact", emergencyContactPhone: "09544883796",
    branchId: "br-cbt", departmentId: "dp-bod", positionId: "ps-chairman-of-the-board-1", supervisorId: null,
    employmentStatus: "regular", dateHired: "2025-07-13", dateRegularized: "2026-01-13",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "monthly", dailyRate: null, monthlySalary: 75000,
    dailyAllowance: null, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["upper_management"],
  },
  {
    id: "emp-002", employeeNumber: nextEmployeeNumber(),
    firstName: "Junrey", lastName: "Japitan", nickname: "Junr",
    gender: "Female", birthdate: "1976-04-08", civilStatus: "Widowed", nationality: "Filipino",
    address: "159 Mabini St., CBT", contactNumber: "09760377693", email: "junrey.japitan@shantahl.com.ph",
    emergencyContactName: "Santos, Emergency Contact", emergencyContactPhone: "09681966606",
    branchId: "br-cbt", departmentId: "dp-bod", positionId: "ps-president-for-cosmetics-2", supervisorId: null,
    employmentStatus: "regular", dateHired: "2024-07-12", dateRegularized: "2025-01-12",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "monthly", dailyRate: null, monthlySalary: 50000,
    dailyAllowance: null, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["upper_management"],
  },
  {
    id: "emp-003", employeeNumber: nextEmployeeNumber(),
    firstName: "Magdadaro", lastName: "Mark Anthony", nickname: "Magd",
    gender: "Female", birthdate: "1977-07-13", civilStatus: "Single", nationality: "Filipino",
    address: "721 Mabini St., CBT", contactNumber: "09155203271", email: "magdadaro.markanthony@shantahl.com.ph",
    emergencyContactName: "Castillo, Emergency Contact", emergencyContactPhone: "09748039203",
    branchId: "br-cbt", departmentId: "dp-bod", positionId: "ps-president-for-darofy-3", supervisorId: null,
    employmentStatus: "regular", dateHired: "2023-07-12", dateRegularized: "2024-01-12",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "monthly", dailyRate: null, monthlySalary: 50000,
    dailyAllowance: null, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["upper_management"],
  },
  {
    id: "emp-004", employeeNumber: nextEmployeeNumber(),
    firstName: "Sheilah", lastName: "Magdadaro", nickname: "Shei",
    gender: "Male", birthdate: "1978-10-18", civilStatus: "Widowed", nationality: "Filipino",
    address: "389 Mabini St., CBT", contactNumber: "09883582018", email: "sheilah.magdadaro@shantahl.com.ph",
    emergencyContactName: "Castillo, Emergency Contact", emergencyContactPhone: "09843379746",
    branchId: "br-cbt", departmentId: "dp-bod", positionId: "ps-vice-chairperson-4", supervisorId: null,
    employmentStatus: "regular", dateHired: "2022-07-11", dateRegularized: "2023-01-11",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "monthly", dailyRate: null, monthlySalary: 35000,
    dailyAllowance: null, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["upper_management"],
  },
  {
    id: "emp-005", employeeNumber: nextEmployeeNumber(),
    firstName: "Maricris", lastName: "Barlinan", nickname: "Mari",
    gender: "Female", birthdate: "1979-01-23", civilStatus: "Single", nationality: "Filipino",
    address: "790 Mabini St., CBT", contactNumber: "09694456749", email: "maricris.barlinan@shantahl.com.ph",
    emergencyContactName: "Cruz, Emergency Contact", emergencyContactPhone: "09893882675",
    branchId: "br-cbt", departmentId: "dp-acctg", positionId: "ps-chief-finance-officer-5", supervisorId: null,
    employmentStatus: "regular", dateHired: "2021-07-10", dateRegularized: "2022-01-10",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "monthly", dailyRate: null, monthlySalary: 20000,
    dailyAllowance: null, monthlyAllowance: 5000,
    status: "active", statusChangedAt: null, roles: ["cfo"],
  },
  {
    id: "emp-006", employeeNumber: nextEmployeeNumber(),
    firstName: "Abigail", lastName: "Caluya", nickname: "Abig",
    gender: "Female", birthdate: "1980-04-03", civilStatus: "Single", nationality: "Filipino",
    address: "495 Mabini St., CBT", contactNumber: "09515648848", email: "abigail.caluya@shantahl.com.ph",
    emergencyContactName: "Garcia, Emergency Contact", emergencyContactPhone: "09649037673",
    branchId: "br-cbt", departmentId: "dp-acctg", positionId: "ps-accounting-clerk-6", supervisorId: "emp-005",
    employmentStatus: "regular", dateHired: "2020-07-09", dateRegularized: "2021-01-09",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 590, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-007", employeeNumber: nextEmployeeNumber(),
    firstName: "Wendie", lastName: "Halog", nickname: "Wend",
    gender: "Female", birthdate: "1981-07-08", civilStatus: "Single", nationality: "Filipino",
    address: "720 Mabini St., CBT", contactNumber: "09775726408", email: "wendie.halog@shantahl.com.ph",
    emergencyContactName: "Garcia, Emergency Contact", emergencyContactPhone: "09325738528",
    branchId: "br-cbt", departmentId: "dp-acctg", positionId: "ps-sr-accounting-assistant-7", supervisorId: "emp-005",
    employmentStatus: "regular", dateHired: "2019-07-09", dateRegularized: "2020-01-09",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 691, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["sr_accounting_assistant", "payroll_officer"],
  },
  {
    id: "emp-008", employeeNumber: nextEmployeeNumber(),
    firstName: "Charmaine", lastName: "Palacio", nickname: "Char",
    gender: "Male", birthdate: "1982-10-13", civilStatus: "Widowed", nationality: "Filipino",
    address: "623 Mabini St., CBT", contactNumber: "09596558039", email: "charmaine.palacio@shantahl.com.ph",
    emergencyContactName: "Torres, Emergency Contact", emergencyContactPhone: "09398102204",
    branchId: "br-cbt", departmentId: "dp-acctg", positionId: "ps-jr-accounting-assistant-8", supervisorId: "emp-005",
    employmentStatus: "regular", dateHired: "2018-07-08", dateRegularized: "2019-01-08",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 671, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-009", employeeNumber: nextEmployeeNumber(),
    firstName: "Kathleen", lastName: "Surigao", nickname: "Kath",
    gender: "Female", birthdate: "1983-01-18", civilStatus: "Widowed", nationality: "Filipino",
    address: "883 Mabini St., CBT", contactNumber: "09799299053", email: "kathleen.surigao@shantahl.com.ph",
    emergencyContactName: "Ramos, Emergency Contact", emergencyContactPhone: "09299216228",
    branchId: "br-cbt", departmentId: "dp-acctg", positionId: "ps-accounting-clerk-6", supervisorId: "emp-005",
    employmentStatus: "regular", dateHired: "2017-07-07", dateRegularized: "2018-01-07",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 590, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-010", employeeNumber: nextEmployeeNumber(),
    firstName: "Erika Grace", lastName: "Bulaclac", nickname: "Erik",
    gender: "Male", birthdate: "1984-04-23", civilStatus: "Single", nationality: "Filipino",
    address: "662 Mabini St., CBT", contactNumber: "09223669959", email: "erikagrace.bulaclac@shantahl.com.ph",
    emergencyContactName: "Santos, Emergency Contact", emergencyContactPhone: "09198070206",
    branchId: "br-cbt", departmentId: "dp-fin", positionId: "ps-bookkeeper-9", supervisorId: "emp-011",
    employmentStatus: "regular", dateHired: "2016-07-06", dateRegularized: "2017-01-06",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 590, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-011", employeeNumber: nextEmployeeNumber(),
    firstName: "Joan Mariette", lastName: "Santarina", nickname: "Joan",
    gender: "Male", birthdate: "1985-07-16", civilStatus: "Single", nationality: "Filipino",
    address: "842 Mabini St., CBT", contactNumber: "09280130817", email: "joanmariette.santarina@shantahl.com.ph",
    emergencyContactName: "Santos, Emergency Contact", emergencyContactPhone: "09503468972",
    branchId: "br-cbt", departmentId: "dp-fin", positionId: "ps-corporate-treasurer-10", supervisorId: "emp-004",
    employmentStatus: "regular", dateHired: "2025-07-03", dateRegularized: "2026-01-03",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 723, monthlySalary: null,
    dailyAllowance: 28, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["treasurer"],
  },
  {
    id: "emp-012", employeeNumber: nextEmployeeNumber(),
    firstName: "Sheena", lastName: "Evangelista", nickname: "Shee",
    gender: "Female", birthdate: "1986-10-08", civilStatus: "Single", nationality: "Filipino",
    address: "146 Mabini St., CBT", contactNumber: "09202523426", email: "sheena.evangelista@shantahl.com.ph",
    emergencyContactName: "Garcia, Emergency Contact", emergencyContactPhone: "09809690825",
    branchId: "br-cbt", departmentId: "dp-hr", positionId: "ps-hr-manager-11", supervisorId: "emp-004",
    employmentStatus: "regular", dateHired: "2024-07-02", dateRegularized: "2025-01-02",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 723, monthlySalary: null,
    dailyAllowance: 28, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["hr_admin"],
  },
  {
    id: "emp-013", employeeNumber: nextEmployeeNumber(),
    firstName: "Angela", lastName: "Acosta", nickname: "Ange",
    gender: "Female", birthdate: "1987-01-13", civilStatus: "Widowed", nationality: "Filipino",
    address: "625 Mabini St., CBT", contactNumber: "09834478972", email: "angela.acosta@shantahl.com.ph",
    emergencyContactName: "Torres, Emergency Contact", emergencyContactPhone: "09251593727",
    branchId: "br-cbt", departmentId: "dp-darofy-mktg", positionId: "ps-content-creator-12", supervisorId: null,
    employmentStatus: "regular", dateHired: "2023-07-02", dateRegularized: "2024-01-02",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 590, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-014", employeeNumber: nextEmployeeNumber(),
    firstName: "Erwin", lastName: "Carreon", nickname: "Erwi",
    gender: "Male", birthdate: "1988-04-18", civilStatus: "Single", nationality: "Filipino",
    address: "366 Mabini St., CBT", contactNumber: "09374213352", email: "erwin.carreon@shantahl.com.ph",
    emergencyContactName: "Cruz, Emergency Contact", emergencyContactPhone: "09640012596",
    branchId: "br-cbt", departmentId: "dp-darofy-mktg", positionId: "ps-content-creator-12", supervisorId: null,
    employmentStatus: "regular", dateHired: "2022-07-01", dateRegularized: "2023-01-01",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 590, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-015", employeeNumber: nextEmployeeNumber(),
    firstName: "Sarah Mae", lastName: "Iglesia", nickname: "Sara",
    gender: "Female", birthdate: "1989-07-23", civilStatus: "Single", nationality: "Filipino",
    address: "200 Mabini St., CBT", contactNumber: "09535272254", email: "sarahmae.iglesia@shantahl.com.ph",
    emergencyContactName: "Santos, Emergency Contact", emergencyContactPhone: "09623635778",
    branchId: "br-cbt", departmentId: "dp-darofy-mktg", positionId: "ps-marketing-head-13", supervisorId: "emp-003",
    employmentStatus: "regular", dateHired: "2021-06-30", dateRegularized: "2021-12-30",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 691, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-016", employeeNumber: nextEmployeeNumber(),
    firstName: "Frank", lastName: "Delos Santos", nickname: "Fran",
    gender: "Female", birthdate: "1990-10-03", civilStatus: "Married", nationality: "Filipino",
    address: "375 Mabini St., CBT", contactNumber: "09623078009", email: "frank.delossantos@shantahl.com.ph",
    emergencyContactName: "Santos, Emergency Contact", emergencyContactPhone: "09397007915",
    branchId: "br-cbt", departmentId: "dp-darofy-mktg", positionId: "ps-multimedia-artist-14", supervisorId: null,
    employmentStatus: "regular", dateHired: "2020-06-29", dateRegularized: "2020-12-29",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 590, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-017", employeeNumber: nextEmployeeNumber(),
    firstName: "Mae", lastName: "Japitan", nickname: "Mae",
    gender: "Male", birthdate: "1991-01-08", civilStatus: "Single", nationality: "Filipino",
    address: "371 Mabini St., CBT", contactNumber: "09769192700", email: "mae.japitan@shantahl.com.ph",
    emergencyContactName: "Bautista, Emergency Contact", emergencyContactPhone: "09179040997",
    branchId: "br-cbt", departmentId: "dp-darofy-sales", positionId: "ps-sales-manager-15", supervisorId: "emp-003",
    employmentStatus: "regular", dateHired: "2019-06-29", dateRegularized: "2019-12-29",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 691, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["dept_head", "employee"],
  },
  {
    id: "emp-018", employeeNumber: nextEmployeeNumber(),
    firstName: "Christian Mharbee", lastName: "Mongcal", nickname: "Chri",
    gender: "Female", birthdate: "1992-04-13", civilStatus: "Single", nationality: "Filipino",
    address: "157 Mabini St., CBT", contactNumber: "09346999412", email: "christianmharbee.mongcal@shantahl.com.ph",
    emergencyContactName: "Ramos, Emergency Contact", emergencyContactPhone: "09603287414",
    branchId: "br-cbt", departmentId: "dp-darofy-sales", positionId: "ps-sales-admin-16", supervisorId: "emp-017",
    employmentStatus: "regular", dateHired: "2018-06-28", dateRegularized: "2018-12-28",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 590, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-019", employeeNumber: nextEmployeeNumber(),
    firstName: "Fernan", lastName: "Barlinan", nickname: "Fern",
    gender: "Male", birthdate: "1993-07-18", civilStatus: "Single", nationality: "Filipino",
    address: "626 Mabini St., CBT", contactNumber: "09108323567", email: "fernan.barlinan@shantahl.com.ph",
    emergencyContactName: "Castillo, Emergency Contact", emergencyContactPhone: "09754806675",
    branchId: "br-cbt", departmentId: "dp-darofy-sales", positionId: "ps-sales-admin-16", supervisorId: "emp-017",
    employmentStatus: "regular", dateHired: "2017-06-27", dateRegularized: "2017-12-27",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 590, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-020", employeeNumber: nextEmployeeNumber(),
    firstName: "Chester", lastName: "Rosales", nickname: "Ches",
    gender: "Female", birthdate: "1994-10-23", civilStatus: "Married", nationality: "Filipino",
    address: "208 Mabini St., MNL", contactNumber: "09718018064", email: "chester.rosales@shantahl.com.ph",
    emergencyContactName: "Torres, Emergency Contact", emergencyContactPhone: "09374864293",
    branchId: "br-mnl", departmentId: "dp-mlm-netdev", positionId: "ps-network-development-head-luzon-17", supervisorId: null,
    employmentStatus: "regular", dateHired: "2016-06-26", dateRegularized: "2016-12-26",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "monthly", dailyRate: null, monthlySalary: 19432,
    dailyAllowance: null, monthlyAllowance: 5568,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-021", employeeNumber: nextEmployeeNumber(),
    firstName: "Randel", lastName: "Segovia", nickname: "Rand",
    gender: "Male", birthdate: "1995-01-03", civilStatus: "Widowed", nationality: "Filipino",
    address: "685 Mabini St., MDU", contactNumber: "09155228070", email: "randel.segovia@shantahl.com.ph",
    emergencyContactName: "Torres, Emergency Contact", emergencyContactPhone: "09835109785",
    branchId: "br-mdu", departmentId: "dp-mlm-netdev", positionId: "ps-network-development-head-visayas-18", supervisorId: null,
    employmentStatus: "regular", dateHired: "2025-06-23", dateRegularized: "2025-12-23",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "monthly", dailyRate: null, monthlySalary: 19432,
    dailyAllowance: null, monthlyAllowance: 5568,
    status: "resigned", statusChangedAt: "2026-07-07", roles: ["employee"],
  },
  {
    id: "emp-022", employeeNumber: nextEmployeeNumber(),
    firstName: "Domecillo", lastName: "Romelito", nickname: "Dome",
    gender: "Female", birthdate: "1996-04-08", civilStatus: "Single", nationality: "Filipino",
    address: "386 Mabini St., MNL", contactNumber: "09657433461", email: "domecillo.romelito@shantahl.com.ph",
    emergencyContactName: "Ramos, Emergency Contact", emergencyContactPhone: "09837355007",
    branchId: "br-mnl", departmentId: "dp-mlm-netdev", positionId: "ps-network-development-head-mindanao-19", supervisorId: null,
    employmentStatus: "regular", dateHired: "2024-06-22", dateRegularized: "2024-12-22",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "monthly", dailyRate: null, monthlySalary: 19432,
    dailyAllowance: null, monthlyAllowance: 5568,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-023", employeeNumber: nextEmployeeNumber(),
    firstName: "John Michael", lastName: "De Maliwat", nickname: "John",
    gender: "Male", birthdate: "1997-07-13", civilStatus: "Single", nationality: "Filipino",
    address: "410 Mabini St., CBT", contactNumber: "09716857942", email: "johnmichael.demaliwat@shantahl.com.ph",
    emergencyContactName: "Bautista, Emergency Contact", emergencyContactPhone: "09310118476",
    branchId: "br-cbt", departmentId: "dp-mlm-mktg", positionId: "ps-multimedia-artist-20", supervisorId: "emp-037",
    employmentStatus: "regular", dateHired: "2023-06-22", dateRegularized: "2023-12-22",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 590, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-024", employeeNumber: nextEmployeeNumber(),
    firstName: "Jaz", lastName: "Eusebio", nickname: "Jaz",
    gender: "Male", birthdate: "1998-10-18", civilStatus: "Widowed", nationality: "Filipino",
    address: "893 Mabini St., CBT", contactNumber: "09564468182", email: "jaz.eusebio@shantahl.com.ph",
    emergencyContactName: "Santos, Emergency Contact", emergencyContactPhone: "09361267731",
    branchId: "br-cbt", departmentId: "dp-mlm-mktg", positionId: "ps-social-media-manager-21", supervisorId: null,
    employmentStatus: "freelance", dateHired: "2022-06-21", dateRegularized: null,
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "monthly", dailyRate: null, monthlySalary: 18000,
    dailyAllowance: null, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-025", employeeNumber: nextEmployeeNumber(),
    firstName: "Renz", lastName: "Nunez", nickname: "Renz",
    gender: "Male", birthdate: "1999-01-23", civilStatus: "Single", nationality: "Filipino",
    address: "832 Mabini St., MNL", contactNumber: "09312321708", email: "renz.nunez@shantahl.com.ph",
    emergencyContactName: "Bautista, Emergency Contact", emergencyContactPhone: "09810023459",
    branchId: "br-mnl", departmentId: "dp-mlm-mktg", positionId: "ps-social-media-manager-21", supervisorId: null,
    employmentStatus: "freelance", dateHired: "2021-06-20", dateRegularized: null,
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 881.79, monthlySalary: null,
    dailyAllowance: 0, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-026", employeeNumber: nextEmployeeNumber(),
    firstName: "Danniel", lastName: "Borja", nickname: "Dann",
    gender: "Female", birthdate: "1975-04-03", civilStatus: "Widowed", nationality: "Filipino",
    address: "798 Mabini St., MNL", contactNumber: "09655959362", email: "danniel.borja@shantahl.com.ph",
    emergencyContactName: "Ramos, Emergency Contact", emergencyContactPhone: "09434923531",
    branchId: "br-mnl", departmentId: "dp-mlm-mktg", positionId: "ps-video-editor-22", supervisorId: null,
    employmentStatus: "freelance", dateHired: "2020-06-19", dateRegularized: null,
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 881.79, monthlySalary: null,
    dailyAllowance: 0, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-027", employeeNumber: nextEmployeeNumber(),
    firstName: "Michelle", lastName: "Ignacio", nickname: "Mich",
    gender: "Male", birthdate: "1976-07-08", civilStatus: "Widowed", nationality: "Filipino",
    address: "832 Mabini St., CBT", contactNumber: "09202863933", email: "michelle.ignacio@shantahl.com.ph",
    emergencyContactName: "Mendoza, Emergency Contact", emergencyContactPhone: "09116476333",
    branchId: "br-cbt", departmentId: "dp-mlm-sales", positionId: "ps-ads-specialist-23", supervisorId: null,
    employmentStatus: "freelance", dateHired: "2019-06-19", dateRegularized: null,
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "monthly", dailyRate: null, monthlySalary: 18000,
    dailyAllowance: null, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-028", employeeNumber: nextEmployeeNumber(),
    firstName: "Eric", lastName: "Ads Specialist", nickname: "Eric",
    gender: "Female", birthdate: "1977-10-13", civilStatus: "Single", nationality: "Filipino",
    address: "351 Mabini St., CEB", contactNumber: "09287144025", email: "eric.adsspecialist@shantahl.com.ph",
    emergencyContactName: "Flores, Emergency Contact", emergencyContactPhone: "09173989182",
    branchId: "br-ceb", departmentId: "dp-mlm-sales", positionId: "ps-ads-specialist-23", supervisorId: null,
    employmentStatus: "freelance", dateHired: "2018-06-18", dateRegularized: null,
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "monthly", dailyRate: null, monthlySalary: 10000,
    dailyAllowance: null, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-029", employeeNumber: nextEmployeeNumber(),
    firstName: "Jennifer", lastName: "Gonzales", nickname: "Jenn",
    gender: "Female", birthdate: "1978-01-18", civilStatus: "Single", nationality: "Filipino",
    address: "817 Mabini St., CBT", contactNumber: "09522888602", email: "jennifer.gonzales@shantahl.com.ph",
    emergencyContactName: "Ramos, Emergency Contact", emergencyContactPhone: "09592651901",
    branchId: "br-cbt", departmentId: "dp-mlm-sales", positionId: "ps-sales-admin-24", supervisorId: "emp-012",
    employmentStatus: "regular", dateHired: "2017-06-17", dateRegularized: "2017-12-17",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 590, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-030", employeeNumber: nextEmployeeNumber(),
    firstName: "Charm", lastName: "Rivera", nickname: "Char",
    gender: "Female", birthdate: "1979-04-23", civilStatus: "Single", nationality: "Filipino",
    address: "570 Mabini St., CBT", contactNumber: "09346510656", email: "charm.rivera@shantahl.com.ph",
    emergencyContactName: "Torres, Emergency Contact", emergencyContactPhone: "09587864915",
    branchId: "br-cbt", departmentId: "dp-mlm-sales", positionId: "ps-sales-admin-24", supervisorId: "emp-012",
    employmentStatus: "regular", dateHired: "2016-06-16", dateRegularized: "2016-12-16",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 590, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-031", employeeNumber: nextEmployeeNumber(),
    firstName: "Jai", lastName: "Jai", nickname: "Jai",
    gender: "Male", birthdate: "1980-07-19", civilStatus: "Single", nationality: "Filipino",
    address: "106 Mabini St., CEB", contactNumber: "09178517533", email: "jai.jai@shantahl.com.ph",
    emergencyContactName: "Torres, Emergency Contact", emergencyContactPhone: "09249762484",
    branchId: "br-ceb", departmentId: "dp-mlm-sales", positionId: "ps-sales-admin-24", supervisorId: "emp-012",
    employmentStatus: "regular", dateHired: "2025-07-13", dateRegularized: "2026-01-13",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 540, monthlySalary: null,
    dailyAllowance: 0, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-032", employeeNumber: nextEmployeeNumber(),
    firstName: "Suzanne", lastName: "Sarona", nickname: "Suza",
    gender: "Male", birthdate: "1981-10-08", civilStatus: "Single", nationality: "Filipino",
    address: "217 Mabini St., CEB", contactNumber: "09421037133", email: "suzanne.sarona@shantahl.com.ph",
    emergencyContactName: "Reyes, Emergency Contact", emergencyContactPhone: "09119699175",
    branchId: "br-ceb", departmentId: "dp-mlm-sales", positionId: "ps-sales-admin-24", supervisorId: "emp-012",
    employmentStatus: "regular", dateHired: "2024-07-12", dateRegularized: "2025-01-12",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 540, monthlySalary: null,
    dailyAllowance: 0, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-033", employeeNumber: nextEmployeeNumber(),
    firstName: "Marissa", lastName: "Camposo", nickname: "Mari",
    gender: "Female", birthdate: "1982-01-13", civilStatus: "Single", nationality: "Filipino",
    address: "279 Mabini St., CEB", contactNumber: "09686325573", email: "marissa.camposo@shantahl.com.ph",
    emergencyContactName: "Santos, Emergency Contact", emergencyContactPhone: "09518323723",
    branchId: "br-ceb", departmentId: "dp-mlm-sales", positionId: "ps-sales-admin-24", supervisorId: "emp-012",
    employmentStatus: "regular", dateHired: "2023-07-12", dateRegularized: "2024-01-12",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 540, monthlySalary: null,
    dailyAllowance: 0, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-034", employeeNumber: nextEmployeeNumber(),
    firstName: "Jerome", lastName: "Canas", nickname: "Jero",
    gender: "Female", birthdate: "1983-04-18", civilStatus: "Married", nationality: "Filipino",
    address: "790 Mabini St., CBT", contactNumber: "09405109318", email: "jerome.canas@shantahl.com.ph",
    emergencyContactName: "Garcia, Emergency Contact", emergencyContactPhone: "09347769338",
    branchId: "br-cbt", departmentId: "dp-cosmetics", positionId: "ps-platform-specialist-25", supervisorId: "emp-002",
    employmentStatus: "regular", dateHired: "2022-07-11", dateRegularized: "2023-01-11",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 590, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-035", employeeNumber: nextEmployeeNumber(),
    firstName: "Loribel", lastName: "Garcia", nickname: "Lori",
    gender: "Male", birthdate: "1984-07-23", civilStatus: "Widowed", nationality: "Filipino",
    address: "221 Mabini St., CBT", contactNumber: "09764742588", email: "loribel.garcia@shantahl.com.ph",
    emergencyContactName: "Mendoza, Emergency Contact", emergencyContactPhone: "09836137296",
    branchId: "br-cbt", departmentId: "dp-cosmetics", positionId: "ps-multimedia-artist-head-26", supervisorId: "emp-002",
    employmentStatus: "regular", dateHired: "2021-07-10", dateRegularized: "2022-01-10",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 606, monthlySalary: null,
    dailyAllowance: null, monthlyAllowance: 4194,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-036", employeeNumber: nextEmployeeNumber(),
    firstName: "Arnie", lastName: "Pangilinan", nickname: "Arni",
    gender: "Male", birthdate: "1985-10-03", civilStatus: "Widowed", nationality: "Filipino",
    address: "736 Mabini St., CBT", contactNumber: "09311053927", email: "arnie.pangilinan@shantahl.com.ph",
    emergencyContactName: "Ramos, Emergency Contact", emergencyContactPhone: "09599946623",
    branchId: "br-cbt", departmentId: "dp-cosmetics", positionId: "ps-video-editor-27", supervisorId: "emp-002",
    employmentStatus: "regular", dateHired: "2020-07-09", dateRegularized: "2021-01-09",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 590, monthlySalary: null,
    dailyAllowance: null, monthlyAllowance: 2611,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-037", employeeNumber: nextEmployeeNumber(),
    firstName: "Ronald", lastName: "Lugtu", nickname: "Rona",
    gender: "Female", birthdate: "1986-01-08", civilStatus: "Single", nationality: "Filipino",
    address: "170 Mabini St., CBT", contactNumber: "09155792455", email: "ronald.lugtu@shantahl.com.ph",
    emergencyContactName: "Castillo, Emergency Contact", emergencyContactPhone: "09337416176",
    branchId: "br-cbt", departmentId: "dp-darofy-marketing-corp", positionId: "ps-multimedia-artist-head-mlm-28", supervisorId: null,
    employmentStatus: "regular", dateHired: "2019-07-09", dateRegularized: "2020-01-09",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 690.1, monthlySalary: null,
    dailyAllowance: null, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-038", employeeNumber: nextEmployeeNumber(),
    firstName: "John Paul Michael", lastName: "Papa", nickname: "John",
    gender: "Male", birthdate: "1987-04-13", civilStatus: "Married", nationality: "Filipino",
    address: "687 Mabini St., CBT", contactNumber: "09373676433", email: "johnpaulmichael.papa@shantahl.com.ph",
    emergencyContactName: "Mendoza, Emergency Contact", emergencyContactPhone: "09610095354",
    branchId: "br-cbt", departmentId: "dp-mlm-mktg", positionId: "ps-multimedia-artist-head-29", supervisorId: null,
    employmentStatus: "regular", dateHired: "2018-07-08", dateRegularized: "2019-01-08",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "monthly", dailyRate: null, monthlySalary: 20000,
    dailyAllowance: null, monthlyAllowance: 5000,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-039", employeeNumber: nextEmployeeNumber(),
    firstName: "Ara Juniella", lastName: "Aling", nickname: "Ara ",
    gender: "Female", birthdate: "1988-07-18", civilStatus: "Married", nationality: "Filipino",
    address: "368 Mabini St., MNL", contactNumber: "09258878968", email: "arajuniella.aling@shantahl.com.ph",
    emergencyContactName: "Bautista, Emergency Contact", emergencyContactPhone: "09566898997",
    branchId: "br-mnl", departmentId: "dp-indie-mktg", positionId: "ps-marketing-assistant-30", supervisorId: "emp-012",
    employmentStatus: "regular", dateHired: "2017-07-07", dateRegularized: "2018-01-07",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 695, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-040", employeeNumber: nextEmployeeNumber(),
    firstName: "Dra.", lastName: "Cecil Catapang", nickname: "Dra.",
    gender: "Female", birthdate: "1989-10-23", civilStatus: "Widowed", nationality: "Filipino",
    address: "155 Mabini St., MNL", contactNumber: "09645182813", email: "dra..cecilcatapang@shantahl.com.ph",
    emergencyContactName: "Flores, Emergency Contact", emergencyContactPhone: "09892212970",
    branchId: "br-mnl", departmentId: "dp-indie-mktg", positionId: "ps-product-specialist-31", supervisorId: null,
    employmentStatus: "freelance", dateHired: "2016-07-06", dateRegularized: null,
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "monthly", dailyRate: null, monthlySalary: 30000,
    dailyAllowance: null, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-041", employeeNumber: nextEmployeeNumber(),
    firstName: "Shegive", lastName: "Lee", nickname: "Sheg",
    gender: "Female", birthdate: "1990-01-03", civilStatus: "Single", nationality: "Filipino",
    address: "256 Mabini St., MNL", contactNumber: "09613933666", email: "shegive.lee@shantahl.com.ph",
    emergencyContactName: "Torres, Emergency Contact", emergencyContactPhone: "09677316062",
    branchId: "br-mnl", departmentId: "dp-indie-mktg", positionId: "ps-product-specialist-31", supervisorId: null,
    employmentStatus: "freelance", dateHired: "2025-07-03", dateRegularized: null,
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "monthly", dailyRate: null, monthlySalary: 25000,
    dailyAllowance: null, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-042", employeeNumber: nextEmployeeNumber(),
    firstName: "Reynalyn", lastName: "Alfonso", nickname: "Reyn",
    gender: "Female", birthdate: "1991-04-08", civilStatus: "Widowed", nationality: "Filipino",
    address: "714 Mabini St., CBT", contactNumber: "09332243271", email: "reynalyn.alfonso@shantahl.com.ph",
    emergencyContactName: "Garcia, Emergency Contact", emergencyContactPhone: "09655059314",
    branchId: "br-cbt", departmentId: "dp-operation", positionId: "ps-cashier-32", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2024-07-02", dateRegularized: "2025-01-02",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 590, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-043", employeeNumber: nextEmployeeNumber(),
    firstName: "Cherry Ann", lastName: "Asuncion", nickname: "Cher",
    gender: "Male", birthdate: "1992-07-13", civilStatus: "Single", nationality: "Filipino",
    address: "770 Mabini St., CBT", contactNumber: "09479548553", email: "cherryann.asuncion@shantahl.com.ph",
    emergencyContactName: "Flores, Emergency Contact", emergencyContactPhone: "09408301147",
    branchId: "br-cbt", departmentId: "dp-operation", positionId: "ps-csr-33", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2023-07-02", dateRegularized: "2024-01-02",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 590, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-044", employeeNumber: nextEmployeeNumber(),
    firstName: "Jomari", lastName: "De Dios", nickname: "Joma",
    gender: "Female", birthdate: "1993-10-18", civilStatus: "Married", nationality: "Filipino",
    address: "453 Mabini St., CBT", contactNumber: "09619536130", email: "jomari.dedios@shantahl.com.ph",
    emergencyContactName: "Reyes, Emergency Contact", emergencyContactPhone: "09442048398",
    branchId: "br-cbt", departmentId: "dp-operation", positionId: "ps-warehouseman-34", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2022-07-01", dateRegularized: "2023-01-01",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 590, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-045", employeeNumber: nextEmployeeNumber(),
    firstName: "Marlyn", lastName: "Leonardo", nickname: "Marl",
    gender: "Female", birthdate: "1994-01-23", civilStatus: "Single", nationality: "Filipino",
    address: "326 Mabini St., CBT", contactNumber: "09640841457", email: "marlyn.leonardo@shantahl.com.ph",
    emergencyContactName: "Flores, Emergency Contact", emergencyContactPhone: "09658435024",
    branchId: "br-cbt", departmentId: "dp-operation", positionId: "ps-operations-manager-35", supervisorId: null,
    employmentStatus: "regular", dateHired: "2021-06-30", dateRegularized: "2021-12-30",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "monthly", dailyRate: null, monthlySalary: 20000,
    dailyAllowance: null, monthlyAllowance: 5000,
    status: "active", statusChangedAt: null, roles: ["dept_head", "employee"],
  },
  {
    id: "emp-046", employeeNumber: nextEmployeeNumber(),
    firstName: "Ronnel", lastName: "Longalong", nickname: "Ronn",
    gender: "Female", birthdate: "1995-04-03", civilStatus: "Widowed", nationality: "Filipino",
    address: "856 Mabini St., CBT", contactNumber: "09698730557", email: "ronnel.longalong@shantahl.com.ph",
    emergencyContactName: "Ramos, Emergency Contact", emergencyContactPhone: "09349894925",
    branchId: "br-cbt", departmentId: "dp-operation", positionId: "ps-driver-messenger-36", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2020-06-29", dateRegularized: "2020-12-29",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 590, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "on_leave", statusChangedAt: "2026-07-11", roles: ["employee"],
  },
  {
    id: "emp-047", employeeNumber: nextEmployeeNumber(),
    firstName: "Twinkle", lastName: "Marayag", nickname: "Twin",
    gender: "Female", birthdate: "1996-07-08", civilStatus: "Single", nationality: "Filipino",
    address: "810 Mabini St., CBT", contactNumber: "09327109754", email: "twinkle.marayag@shantahl.com.ph",
    emergencyContactName: "Torres, Emergency Contact", emergencyContactPhone: "09630285605",
    branchId: "br-cbt", departmentId: "dp-operation", positionId: "ps-logistics-staff-37", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2019-06-29", dateRegularized: "2019-12-29",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 590, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-048", employeeNumber: nextEmployeeNumber(),
    firstName: "Jaimie", lastName: "Nucom", nickname: "Jaim",
    gender: "Male", birthdate: "1997-10-13", civilStatus: "Single", nationality: "Filipino",
    address: "895 Mabini St., CBT", contactNumber: "09337570350", email: "jaimie.nucom@shantahl.com.ph",
    emergencyContactName: "Cruz, Emergency Contact", emergencyContactPhone: "09365641031",
    branchId: "br-cbt", departmentId: "dp-operation", positionId: "ps-operations-supervisor-38", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2018-06-28", dateRegularized: "2018-12-28",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 691, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-049", employeeNumber: nextEmployeeNumber(),
    firstName: "Felix Ardee", lastName: "Santarina", nickname: "Feli",
    gender: "Female", birthdate: "1998-01-18", civilStatus: "Married", nationality: "Filipino",
    address: "680 Mabini St., CBT", contactNumber: "09643830844", email: "felixardee.santarina@shantahl.com.ph",
    emergencyContactName: "Cruz, Emergency Contact", emergencyContactPhone: "09395592550",
    branchId: "br-cbt", departmentId: "dp-operation", positionId: "ps-logistics-staff-37", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2017-06-27", dateRegularized: "2017-12-27",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 590, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-050", employeeNumber: nextEmployeeNumber(),
    firstName: "Daiki", lastName: "Yamakawa", nickname: "Daik",
    gender: "Male", birthdate: "1999-04-23", civilStatus: "Single", nationality: "Filipino",
    address: "487 Mabini St., CBT", contactNumber: "09871326587", email: "daiki.yamakawa@shantahl.com.ph",
    emergencyContactName: "Cruz, Emergency Contact", emergencyContactPhone: "09204643870",
    branchId: "br-cbt", departmentId: "dp-operation", positionId: "ps-utility-39", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2016-06-26", dateRegularized: "2016-12-26",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 590, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-051", employeeNumber: nextEmployeeNumber(),
    firstName: "Aboguin", lastName: "Ma. Abegail Fatima", nickname: "Abog",
    gender: "Male", birthdate: "1975-07-31", civilStatus: "Single", nationality: "Filipino",
    address: "716 Mabini St., MNL", contactNumber: "09707497574", email: "aboguin.ma.abegailfatima@shantahl.com.ph",
    emergencyContactName: "Flores, Emergency Contact", emergencyContactPhone: "09851757640",
    branchId: "br-mnl", departmentId: "dp-operation", positionId: "ps-branch-supervisor-40", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2025-06-23", dateRegularized: "2025-12-23",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 715, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-052", employeeNumber: nextEmployeeNumber(),
    firstName: "Abegail", lastName: "Bordaje", nickname: "Abeg",
    gender: "Female", birthdate: "1976-10-08", civilStatus: "Widowed", nationality: "Filipino",
    address: "888 Mabini St., MNL", contactNumber: "09806010398", email: "abegail.bordaje@shantahl.com.ph",
    emergencyContactName: "Castillo, Emergency Contact", emergencyContactPhone: "09620431406",
    branchId: "br-mnl", departmentId: "dp-operation", positionId: "ps-cashier-32", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2024-06-22", dateRegularized: "2024-12-22",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 695, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-053", employeeNumber: nextEmployeeNumber(),
    firstName: "Dayanara", lastName: "Flores", nickname: "Daya",
    gender: "Male", birthdate: "1977-01-13", civilStatus: "Single", nationality: "Filipino",
    address: "846 Mabini St., MNL", contactNumber: "09737681564", email: "dayanara.flores@shantahl.com.ph",
    emergencyContactName: "Flores, Emergency Contact", emergencyContactPhone: "09710273978",
    branchId: "br-mnl", departmentId: "dp-operation", positionId: "ps-cashier-32", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2023-06-22", dateRegularized: "2023-12-22",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 695, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-054", employeeNumber: nextEmployeeNumber(),
    firstName: "Jemuel", lastName: "Castillo", nickname: "Jemu",
    gender: "Male", birthdate: "1978-04-18", civilStatus: "Widowed", nationality: "Filipino",
    address: "899 Mabini St., MNL", contactNumber: "09842755432", email: "jemuel.castillo@shantahl.com.ph",
    emergencyContactName: "Mendoza, Emergency Contact", emergencyContactPhone: "09487314626",
    branchId: "br-mnl", departmentId: "dp-operation", positionId: "ps-warehouseman-34", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2022-06-21", dateRegularized: "2022-12-21",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 695, monthlySalary: null,
    dailyAllowance: 47, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-055", employeeNumber: nextEmployeeNumber(),
    firstName: "Girlie Gail", lastName: "Gallardo", nickname: "Girl",
    gender: "Female", birthdate: "1979-07-23", civilStatus: "Married", nationality: "Filipino",
    address: "440 Mabini St., MNL", contactNumber: "09355178039", email: "girliegail.gallardo@shantahl.com.ph",
    emergencyContactName: "Garcia, Emergency Contact", emergencyContactPhone: "09365236199",
    branchId: "br-mnl", departmentId: "dp-operation", positionId: "ps-branch-manager-41", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2021-06-20", dateRegularized: "2021-12-20",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 754, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["dept_head", "employee"],
  },
  {
    id: "emp-056", employeeNumber: nextEmployeeNumber(),
    firstName: "Clover", lastName: "Riomalos", nickname: "Clov",
    gender: "Male", birthdate: "1980-10-03", civilStatus: "Widowed", nationality: "Filipino",
    address: "491 Mabini St., MNL", contactNumber: "09820084918", email: "clover.riomalos@shantahl.com.ph",
    emergencyContactName: "Santos, Emergency Contact", emergencyContactPhone: "09684302189",
    branchId: "br-mnl", departmentId: "dp-operation", positionId: "ps-cashier-32", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2020-06-19", dateRegularized: "2020-12-19",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 695, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-057", employeeNumber: nextEmployeeNumber(),
    firstName: "Bersabal", lastName: "Jober", nickname: "Bers",
    gender: "Male", birthdate: "1981-01-08", civilStatus: "Married", nationality: "Filipino",
    address: "334 Mabini St., CEB", contactNumber: "09271003000", email: "bersabal.jober@shantahl.com.ph",
    emergencyContactName: "Mendoza, Emergency Contact", emergencyContactPhone: "09841398099",
    branchId: "br-ceb", departmentId: "dp-operation", positionId: "ps-driver-warehouseman-42", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2019-06-19", dateRegularized: "2019-12-19",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 540, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-058", employeeNumber: nextEmployeeNumber(),
    firstName: "Karlou James", lastName: "Japitan", nickname: "Karl",
    gender: "Male", birthdate: "1982-04-13", civilStatus: "Single", nationality: "Filipino",
    address: "511 Mabini St., MDU", contactNumber: "09310371303", email: "karloujames.japitan@shantahl.com.ph",
    emergencyContactName: "Garcia, Emergency Contact", emergencyContactPhone: "09688462772",
    branchId: "br-mdu", departmentId: "dp-operation", positionId: "ps-branch-supervisor-40", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2018-06-18", dateRegularized: "2018-12-18",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 646, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-059", employeeNumber: nextEmployeeNumber(),
    firstName: "Ricky", lastName: "Malasa", nickname: "Rick",
    gender: "Female", birthdate: "1983-07-18", civilStatus: "Single", nationality: "Filipino",
    address: "784 Mabini St., MDU", contactNumber: "09764522872", email: "ricky.malasa@shantahl.com.ph",
    emergencyContactName: "Santos, Emergency Contact", emergencyContactPhone: "09548025632",
    branchId: "br-mdu", departmentId: "dp-operation", positionId: "ps-stockman-43", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2017-06-17", dateRegularized: "2017-12-17",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 540, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-060", employeeNumber: nextEmployeeNumber(),
    firstName: "Mary Jane", lastName: "Pedrano", nickname: "Mary",
    gender: "Female", birthdate: "1984-10-23", civilStatus: "Married", nationality: "Filipino",
    address: "536 Mabini St., MDU", contactNumber: "09761596281", email: "maryjane.pedrano@shantahl.com.ph",
    emergencyContactName: "Torres, Emergency Contact", emergencyContactPhone: "09387210965",
    branchId: "br-mdu", departmentId: "dp-operation", positionId: "ps-branch-manager-41", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2016-06-16", dateRegularized: "2016-12-16",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 670, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["dept_head", "employee"],
  },
  {
    id: "emp-061", employeeNumber: nextEmployeeNumber(),
    firstName: "Leonilyn", lastName: "Talisic", nickname: "Leon",
    gender: "Female", birthdate: "1985-01-03", civilStatus: "Single", nationality: "Filipino",
    address: "269 Mabini St., MDU", contactNumber: "09722825985", email: "leonilyn.talisic@shantahl.com.ph",
    emergencyContactName: "Santos, Emergency Contact", emergencyContactPhone: "09752102555",
    branchId: "br-mdu", departmentId: "dp-operation", positionId: "ps-cashier-32", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2025-07-13", dateRegularized: "2026-01-13",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 629, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "resigned", statusChangedAt: "2026-06-25", roles: ["employee"],
  },
  {
    id: "emp-062", employeeNumber: nextEmployeeNumber(),
    firstName: "Gretchen", lastName: "De Sosa", nickname: "Gret",
    gender: "Male", birthdate: "1986-04-08", civilStatus: "Widowed", nationality: "Filipino",
    address: "806 Mabini St., CAV", contactNumber: "09878052626", email: "gretchen.desosa@shantahl.com.ph",
    emergencyContactName: "Bautista, Emergency Contact", emergencyContactPhone: "09878196373",
    branchId: "br-cav", departmentId: "dp-operation", positionId: "ps-cashier-32", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2024-07-12", dateRegularized: "2025-01-12",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 600, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-063", employeeNumber: nextEmployeeNumber(),
    firstName: "Rhea", lastName: "Francisco", nickname: "Rhea",
    gender: "Female", birthdate: "1987-07-13", civilStatus: "Single", nationality: "Filipino",
    address: "659 Mabini St., CAV", contactNumber: "09615246744", email: "rhea.francisco@shantahl.com.ph",
    emergencyContactName: "Reyes, Emergency Contact", emergencyContactPhone: "09490490010",
    branchId: "br-cav", departmentId: "dp-operation", positionId: "ps-cashier-32", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2023-07-12", dateRegularized: "2024-01-12",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 600, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-064", employeeNumber: nextEmployeeNumber(),
    firstName: "Jemima", lastName: "Amestoso", nickname: "Jemi",
    gender: "Male", birthdate: "1988-10-18", civilStatus: "Single", nationality: "Filipino",
    address: "733 Mabini St., CDO", contactNumber: "09836011136", email: "jemima.amestoso@shantahl.com.ph",
    emergencyContactName: "Ramos, Emergency Contact", emergencyContactPhone: "09889433095",
    branchId: "br-cdo", departmentId: "dp-operation", positionId: "ps-cashier-32", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2022-07-11", dateRegularized: "2023-01-11",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 500, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-065", employeeNumber: nextEmployeeNumber(),
    firstName: "Daniel", lastName: "Bato", nickname: "Dani",
    gender: "Female", birthdate: "1989-01-23", civilStatus: "Widowed", nationality: "Filipino",
    address: "267 Mabini St., PGS", contactNumber: "09581223383", email: "daniel.bato@shantahl.com.ph",
    emergencyContactName: "Bautista, Emergency Contact", emergencyContactPhone: "09133993434",
    branchId: "br-pgs", departmentId: "dp-operation", positionId: "ps-cashier-32", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2021-07-10", dateRegularized: "2022-01-10",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 505, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-066", employeeNumber: nextEmployeeNumber(),
    firstName: "Charles", lastName: "Villaflor", nickname: "Char",
    gender: "Male", birthdate: "1990-04-03", civilStatus: "Single", nationality: "Filipino",
    address: "746 Mabini St., DVO", contactNumber: "09765300255", email: "charles.villaflor@shantahl.com.ph",
    emergencyContactName: "Cruz, Emergency Contact", emergencyContactPhone: "09757668712",
    branchId: "br-dvo", departmentId: "dp-operation", positionId: "ps-cashier-32", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2020-07-09", dateRegularized: "2021-01-09",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 510, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-067", employeeNumber: nextEmployeeNumber(),
    firstName: "Jebeth", lastName: "Guinto", nickname: "Jebe",
    gender: "Male", birthdate: "1991-07-08", civilStatus: "Widowed", nationality: "Filipino",
    address: "335 Mabini St., LCN", contactNumber: "09678580673", email: "jebeth.guinto@shantahl.com.ph",
    emergencyContactName: "Castillo, Emergency Contact", emergencyContactPhone: "09110380464",
    branchId: "br-lcn", departmentId: "dp-operation", positionId: "ps-cashier-32", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2019-07-09", dateRegularized: "2020-01-09",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 600, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
  {
    id: "emp-068", employeeNumber: nextEmployeeNumber(),
    firstName: "Catherine", lastName: "Mogato", nickname: "Cath",
    gender: "Male", birthdate: "1992-10-13", civilStatus: "Single", nationality: "Filipino",
    address: "609 Mabini St., BCD", contactNumber: "09763921498", email: "catherine.mogato@shantahl.com.ph",
    emergencyContactName: "Ramos, Emergency Contact", emergencyContactPhone: "09317860781",
    branchId: "br-bcd", departmentId: "dp-operation", positionId: "ps-cashier-32", supervisorId: "emp-045",
    employmentStatus: "regular", dateHired: "2018-07-08", dateRegularized: "2019-01-08",
    contractStart: null, contractEnd: null, probationEndsAt: null,
    payrollType: "daily", dailyRate: 480, monthlySalary: null,
    dailyAllowance: 22, monthlyAllowance: null,
    status: "active", statusChangedAt: null, roles: ["employee"],
  },
];

// --- Named references into the real roster, used to wire demo logins and
// seed audit/discipline records below. ---------------------------------------
const hrManager = EMPLOYEES.find((e) => e.id === "emp-012")!; // Sheena Evangelista, HR Manager
const srAcctgPayroll = EMPLOYEES.find((e) => e.id === "emp-007")!; // Wendie Halog, Sr. Accounting Assistant & Payroll Officer
const treasurer = EMPLOYEES.find((e) => e.id === "emp-011")!; // Joan Mariette Santarina, Corporate Treasurer
const cfo = EMPLOYEES.find((e) => e.id === "emp-005")!; // Maricris Barlinan, CFO
const opsManagerCbt = EMPLOYEES.find((e) => e.id === "emp-045")!; // Marlyn Leonardo, Operations Manager (Cabanatuan)
const cashierReynalyn = EMPLOYEES.find((e) => e.id === "emp-042")!; // Reynalyn Alfonso, Cashier (Cabanatuan)
const viceChair = EMPLOYEES.find((e) => e.id === "emp-004")!; // Sheilah A. Magdadaro, Vice Chairperson

// --- Demo login users -----------------------------------------------------
export const DEMO_USERS: DemoUser[] = [
  { id: "u-hr", employeeId: hrManager.id, name: "Sheena Evangelista", title: "HR Manager", roles: ["hr_admin"], initials: "SE" },
  { id: "u-acctg", employeeId: srAcctgPayroll.id, name: "Wendie Halog", title: "Sr. Accounting Assistant & Payroll Officer", roles: ["sr_accounting_assistant", "payroll_officer"], initials: "WH" },
  { id: "u-treasurer", employeeId: treasurer.id, name: "Joan Mariette Santarina", title: "Corporate Treasurer", roles: ["treasurer"], initials: "JS" },
  { id: "u-cfo", employeeId: cfo.id, name: "Maricris Barlinan", title: "Chief Finance Officer", roles: ["cfo"], initials: "MB" },
  { id: "u-depthead", employeeId: opsManagerCbt.id, name: "Marlyn Leonardo", title: "Operations Manager (Cabanatuan Branch)", roles: ["dept_head", "employee"], initials: "ML" },
  { id: "u-employee", employeeId: cashierReynalyn.id, name: "Reynalyn Alfonso", title: "Cashier (Cabanatuan Branch)", roles: ["employee"], initials: "RA" },
  { id: "u-upper", employeeId: viceChair.id, name: "Sheilah A. Magdadaro", title: "Vice Chairperson", roles: ["upper_management"], initials: "SM" },
];

// --- Leave requests -----------------------------------------------------------
export const LEAVE_REQUESTS: LeaveRequest[] = [
  { id: "lv-1", employeeId: "emp-042", leaveTypeId: "lt-vl", startDate: addDays(TODAY, 7), endDate: addDays(TODAY, 9), days: 3, reason: "Family reunion out of town.", status: "pending", filedAt: addDays(TODAY, -1), decidedBy: null, decidedAt: null, decisionNote: null },
  { id: "lv-2", employeeId: "emp-006", leaveTypeId: "lt-sl", startDate: addDays(TODAY, -8), endDate: addDays(TODAY, -7), days: 2, reason: "Flu with fever.", status: "approved", filedAt: addDays(TODAY, -9), decidedBy: "emp-005", decidedAt: addDays(TODAY, -8), decisionNote: "Get well soon." },
  { id: "lv-3", employeeId: "emp-044", leaveTypeId: "lt-el", startDate: addDays(TODAY, -3), endDate: addDays(TODAY, -3), days: 1, reason: "Family emergency.", status: "approved", filedAt: addDays(TODAY, -3), decidedBy: "emp-045", decidedAt: addDays(TODAY, -3), decisionNote: "Approved." },
  { id: "lv-4", employeeId: "emp-018", leaveTypeId: "lt-vl", startDate: "2026-06-15", endDate: "2026-06-16", days: 2, reason: "Personal travel.", status: "rejected", filedAt: "2026-06-05", decidedBy: "emp-017", decidedAt: "2026-06-06", decisionNote: "Insufficient sales floor coverage that week — please refile for a later date." },
  { id: "lv-5", employeeId: "emp-043", leaveTypeId: "lt-bl", startDate: addDays(TODAY, -5), endDate: addDays(TODAY, -3), days: 3, reason: "Bereavement — immediate family.", status: "approved", filedAt: addDays(TODAY, -6), decidedBy: "emp-045", decidedAt: addDays(TODAY, -6), decisionNote: "Our condolences. Approved." },
  { id: "lv-6", employeeId: "emp-039", leaveTypeId: "lt-vl", startDate: addDays(TODAY, 12), endDate: addDays(TODAY, 14), days: 3, reason: "Pre-planned vacation.", status: "pending", filedAt: addDays(TODAY, -2), decidedBy: null, decidedAt: null, decisionNote: null },
  { id: "lv-7", employeeId: "emp-009", leaveTypeId: "lt-sl", startDate: addDays(TODAY, -13), endDate: addDays(TODAY, -13), days: 1, reason: "Dental procedure.", status: "approved", filedAt: addDays(TODAY, -14), decidedBy: "emp-005", decidedAt: addDays(TODAY, -13), decisionNote: "Approved." },
  { id: "lv-8", employeeId: "emp-052", leaveTypeId: "lt-vl", startDate: addDays(TODAY, 4), endDate: addDays(TODAY, 4), days: 1, reason: "Sibling's wedding.", status: "pending", filedAt: addDays(TODAY, -1), decidedBy: null, decidedAt: null, decisionNote: null },
  { id: "lv-9", employeeId: "emp-061", leaveTypeId: "lt-spl", startDate: addDays(TODAY, -20), endDate: addDays(TODAY, -20), days: 1, reason: "School enrollment for dependent.", status: "approved", filedAt: addDays(TODAY, -21), decidedBy: "emp-045", decidedAt: addDays(TODAY, -20), decisionNote: "Approved." },
  { id: "lv-10", employeeId: "emp-019", leaveTypeId: "lt-el", startDate: addDays(TODAY, 2), endDate: addDays(TODAY, 2), days: 1, reason: "Utility repair at home requires my presence.", status: "pending", filedAt: TODAY, decidedBy: null, decidedAt: null, decisionNote: null },
];

// --- Overtime requests ---------------------------------------------------------
export const OVERTIME_REQUESTS: OvertimeRequest[] = [
  { id: "ot-1", employeeId: "emp-042", date: addDays(TODAY, -2), hours: 3, reason: "Month-end inventory count.", status: "approved", filedAt: addDays(TODAY, -2), decidedBy: "emp-045", decidedAt: addDays(TODAY, -1), decisionNote: "Approved." },
  { id: "ot-2", employeeId: "emp-048", date: addDays(TODAY, -4), hours: 4, reason: "Warehouse stock reconciliation before audit.", status: "approved", filedAt: addDays(TODAY, -4), decidedBy: "emp-045", decidedAt: addDays(TODAY, -3), decisionNote: "Approved." },
  { id: "ot-3", employeeId: "emp-055", date: addDays(TODAY, -1), hours: 2, reason: "Branch closing delayed by system upgrade.", status: "pending", filedAt: addDays(TODAY, -1), decidedBy: null, decidedAt: null, decisionNote: null },
  { id: "ot-4", employeeId: "emp-006", date: addDays(TODAY, -6), hours: 2.5, reason: "Assisting with July payroll prep.", status: "approved", filedAt: addDays(TODAY, -6), decidedBy: "emp-005", decidedAt: addDays(TODAY, -5), decisionNote: "Approved." },
  { id: "ot-5", employeeId: "emp-053", date: addDays(TODAY, -3), hours: 3, reason: "Restocking ahead of weekend promo.", status: "rejected", filedAt: addDays(TODAY, -3), decidedBy: "emp-045", decidedAt: addDays(TODAY, -2), decisionNote: "OT budget for the branch already met this period." },
  { id: "ot-6", employeeId: "emp-029", date: addDays(TODAY, -7), hours: 2, reason: "Sales report backlog.", status: "approved", filedAt: addDays(TODAY, -7), decidedBy: "emp-012", decidedAt: addDays(TODAY, -6), decisionNote: "Approved." },
  { id: "ot-7", employeeId: "emp-062", date: addDays(TODAY, 1), hours: 3, reason: "Coverage for branch inventory tomorrow.", status: "pending", filedAt: TODAY, decidedBy: null, decidedAt: null, decisionNote: null },
];

// --- Attendance correction requests --------------------------------------------
export const CORRECTION_REQUESTS: AttendanceCorrectionRequest[] = [
  { id: "ac-1", employeeId: "emp-042", date: addDays(TODAY, -5), requestedTimeIn: "08:00", requestedTimeOut: "17:00", reason: "Biometric device offline that morning; logged in manually with supervisor.", status: "approved", filedAt: addDays(TODAY, -5), decidedBy: "emp-045", decidedAt: addDays(TODAY, -4), decisionNote: "Confirmed with branch supervisor. Approved." },
  { id: "ac-2", employeeId: "emp-054", date: addDays(TODAY, -2), requestedTimeIn: "08:00", requestedTimeOut: null, reason: "Forgot to time out — left through the back entrance.", status: "pending", filedAt: addDays(TODAY, -1), decidedBy: null, decidedAt: null, decisionNote: null },
  { id: "ac-3", employeeId: "emp-057", date: addDays(TODAY, -9), requestedTimeIn: "06:00", requestedTimeOut: "15:00", reason: "Worked the early shift for a swapped schedule but system still shows default shift hours.", status: "approved", filedAt: addDays(TODAY, -9), decidedBy: "emp-045", decidedAt: addDays(TODAY, -8), decisionNote: "Shift swap confirmed. Approved." },
  { id: "ac-4", employeeId: "emp-064", date: addDays(TODAY, -10), requestedTimeIn: "08:15", requestedTimeOut: "17:00", reason: "Traffic due to road closure; arrived slightly late but was not reflected correctly.", status: "rejected", filedAt: addDays(TODAY, -9), decidedBy: "emp-045", decidedAt: addDays(TODAY, -8), decisionNote: "Late arrival stands — no supporting certificate for road closure." },
];

// --- Attendance period records ------------------------------------------------
// Seeded from the company's own May 1-15, 2026 attendance-tracker export, for
// the 54 employees whose name matched the system roster exactly. The
// remaining rows (new hires / name variants not yet reconciled) are
// intentionally left out — see the Attendance module's import reconciliation
// report.
export const ATTENDANCE_PERIOD_RECORDS: AttendancePeriodRecord[] = [
  { id: "att-seed-1", periodId: "pp-1", employeeId: "emp-051", daysWorked: 11, holidayDays: 1, slDays: 0, vlDays: 1, lateAdjMinutes: 2400, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-2", periodId: "pp-1", employeeId: "emp-042", daysWorked: 12, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-3", periodId: "pp-1", employeeId: "emp-039", daysWorked: 10, holidayDays: 1, slDays: 0, vlDays: 1, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-4", periodId: "pp-1", employeeId: "emp-064", daysWorked: 12, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-5", periodId: "pp-1", employeeId: "emp-043", daysWorked: 12, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-6", periodId: "pp-1", employeeId: "emp-005", daysWorked: 0, holidayDays: 0, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-7", periodId: "pp-1", employeeId: "emp-065", daysWorked: 12, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-8", periodId: "pp-1", employeeId: "emp-052", daysWorked: 11, holidayDays: 1, slDays: 0, vlDays: 1, lateAdjMinutes: 2400, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-9", periodId: "pp-1", employeeId: "emp-010", daysWorked: 11.5, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-10", periodId: "pp-1", employeeId: "emp-006", daysWorked: 12, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-11", periodId: "pp-1", employeeId: "emp-034", daysWorked: 12, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-12", periodId: "pp-1", employeeId: "emp-014", daysWorked: 10.5, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-13", periodId: "pp-1", employeeId: "emp-054", daysWorked: 13, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 2700, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-14", periodId: "pp-1", employeeId: "emp-044", daysWorked: 12, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-15", periodId: "pp-1", employeeId: "emp-012", daysWorked: 9.5, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-16", periodId: "pp-1", employeeId: "emp-053", daysWorked: 12, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 2640, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-17", periodId: "pp-1", employeeId: "emp-063", daysWorked: 0, holidayDays: 0, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-18", periodId: "pp-1", employeeId: "emp-055", daysWorked: 9.5, holidayDays: 1, slDays: 0, vlDays: 2, lateAdjMinutes: 1920, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-19", periodId: "pp-1", employeeId: "emp-035", daysWorked: 11, holidayDays: 1, slDays: 1, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-20", periodId: "pp-1", employeeId: "emp-067", daysWorked: 12, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-21", periodId: "pp-1", employeeId: "emp-007", daysWorked: 11.5, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-22", periodId: "pp-1", employeeId: "emp-015", daysWorked: 10, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-23", periodId: "pp-1", employeeId: "emp-002", daysWorked: 0, holidayDays: 0, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-24", periodId: "pp-1", employeeId: "emp-058", daysWorked: 12, holidayDays: 1.9, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-25", periodId: "pp-1", employeeId: "emp-017", daysWorked: 0, holidayDays: 0, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-26", periodId: "pp-1", employeeId: "emp-045", daysWorked: 0, holidayDays: 0, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-27", periodId: "pp-1", employeeId: "emp-046", daysWorked: 11, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-28", periodId: "pp-1", employeeId: "emp-037", daysWorked: 0, holidayDays: 0, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-29", periodId: "pp-1", employeeId: "emp-001", daysWorked: 0, holidayDays: 0, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-30", periodId: "pp-1", employeeId: "emp-004", daysWorked: 0, holidayDays: 0, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-31", periodId: "pp-1", employeeId: "emp-059", daysWorked: 12, holidayDays: 1.9, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-32", periodId: "pp-1", employeeId: "emp-047", daysWorked: 12, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-33", periodId: "pp-1", employeeId: "emp-068", daysWorked: 12, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-34", periodId: "pp-1", employeeId: "emp-018", daysWorked: 10, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-35", periodId: "pp-1", employeeId: "emp-048", daysWorked: 12, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-36", periodId: "pp-1", employeeId: "emp-008", daysWorked: 11.5, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-37", periodId: "pp-1", employeeId: "emp-036", daysWorked: 11, holidayDays: 1, slDays: 0, vlDays: 1, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-38", periodId: "pp-1", employeeId: "emp-038", daysWorked: 0, holidayDays: 0, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-39", periodId: "pp-1", employeeId: "emp-060", daysWorked: 12, holidayDays: 1.9, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-40", periodId: "pp-1", employeeId: "emp-056", daysWorked: 12, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 2640, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-41", periodId: "pp-1", employeeId: "emp-020", daysWorked: 0, holidayDays: 0, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-42", periodId: "pp-1", employeeId: "emp-049", daysWorked: 11, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-43", periodId: "pp-1", employeeId: "emp-011", daysWorked: 12, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-44", periodId: "pp-1", employeeId: "emp-021", daysWorked: 0, holidayDays: 0, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-45", periodId: "pp-1", employeeId: "emp-009", daysWorked: 11, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-46", periodId: "pp-1", employeeId: "emp-061", daysWorked: 12, holidayDays: 1.9, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-47", periodId: "pp-1", employeeId: "emp-050", daysWorked: 11, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-48", periodId: "pp-1", employeeId: "emp-026", daysWorked: 11, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-49", periodId: "pp-1", employeeId: "emp-019", daysWorked: 8.5, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-50", periodId: "pp-1", employeeId: "emp-062", daysWorked: 10.5, holidayDays: 1, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-51", periodId: "pp-1", employeeId: "emp-033", daysWorked: 12, holidayDays: 1.9, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-52", periodId: "pp-1", employeeId: "emp-032", daysWorked: 12, holidayDays: 1.9, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-53", periodId: "pp-1", employeeId: "emp-013", daysWorked: 0, holidayDays: 0, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
  { id: "att-seed-54", periodId: "pp-1", employeeId: "emp-029", daysWorked: 0, holidayDays: 0, slDays: 0, vlDays: 0, lateAdjMinutes: 0, notes: "", source: "import", updatedBy: "Sheena Evangelista", updatedAt: TODAY },
];

// --- Performance evaluations ------------------------------------------------
export const EVAL_CRITERIA_TEMPLATE = [
  { label: "Job Knowledge", weight: 0.25 },
  { label: "Quality of Work", weight: 0.25 },
  { label: "Attendance & Punctuality", weight: 0.2 },
  { label: "Teamwork", weight: 0.15 },
  { label: "Initiative", weight: 0.15 },
];

function makeEvaluation(id: string, employeeId: string, evaluatorId: string, period: string, status: PerformanceEvaluation["status"], seedOffset: number): PerformanceEvaluation {
  let weighted = 0;
  const criteria = EVAL_CRITERIA_TEMPLATE.map((c, i) => {
    const score = 3 + Math.round(rng() * 2 * 10) / 10 - ((i + seedOffset) % 2) * 0.4;
    const clamped = Math.min(5, Math.max(2, Math.round(score * 10) / 10));
    weighted += clamped * c.weight;
    return { ...c, score: clamped };
  });
  return {
    id,
    employeeId,
    evaluatorId,
    period,
    criteria,
    overallScore: Math.round(weighted * 10) / 10,
    comments:
      weighted >= 4.2
        ? "Consistently exceeds expectations; recommended for recognition."
        : weighted >= 3.5
          ? "Meets expectations with room to grow in initiative."
          : "Needs improvement; performance improvement plan to be discussed.",
    status,
    createdAt: addDays(TODAY, -seedOffset * 4 - 3),
  };
}

export const PERFORMANCE_EVALUATIONS: PerformanceEvaluation[] = [];
export const CURRENT_EVAL_PERIOD = "Semi-Annual 2026 (Jan–Jun)";
const evalPeriod = CURRENT_EVAL_PERIOD;
let evalSeq = 0;
EMPLOYEES.filter((e) => e.roles.includes("employee") && e.supervisorId).forEach((e, i) => {
  if (i % 3 !== 0) return; // sample subset
  evalSeq += 1;
  const status: PerformanceEvaluation["status"] = evalSeq % 3 === 0 ? "draft" : evalSeq % 3 === 1 ? "acknowledged" : "submitted";
  PERFORMANCE_EVALUATIONS.push(
    makeEvaluation(`ev-${evalSeq}`, e.id, e.supervisorId as string, evalPeriod, status, evalSeq),
  );
});

// --- Disciplinary records ---------------------------------------------------
const DISC_TYPES: DisciplinaryRecord["type"][] = [
  "incident_report", "verbal_warning", "written_warning", "suspension", "nte", "nod",
];
const DISC_DESCRIPTIONS: Record<DisciplinaryRecord["type"], string> = {
  incident_report: "Reported for repeated tardiness beyond grace period during the pay period.",
  verbal_warning: "Verbally counseled regarding uniform/dress code compliance.",
  written_warning: "Written warning issued for unauthorized absence without prior notice.",
  suspension: "Three (3) day suspension for violation of company code of conduct.",
  nte: "Notice to Explain issued regarding discrepancy in sales report submission.",
  nod: "Notice of Decision issued following completed administrative investigation.",
};

export const DISCIPLINARY_RECORDS: DisciplinaryRecord[] = [];
const discEmployees = EMPLOYEES.filter((e) => e.roles.includes("employee")).slice(0, 12);
discEmployees.forEach((e, i) => {
  const type = DISC_TYPES[i % DISC_TYPES.length];
  DISCIPLINARY_RECORDS.push({
    id: `disc-${i + 1}`,
    employeeId: e.id,
    type,
    description: DISC_DESCRIPTIONS[type],
    issuedBy: hrManager.id,
    date: addDays(TODAY, -(i * 9 + 5)),
    status: i % 3 === 0 ? "resolved" : "open",
    attachmentName: i % 2 === 0 ? `${type}-${e.employeeNumber}.pdf` : null,
  });
});

// --- Audit logs --------------------------------------------------------------
export const AUDIT_LOGS: AuditLog[] = [
  { id: "al-1", userId: hrManager.id, userName: "Sheena Evangelista", module: "Employee 201 File", action: "update", description: "Updated contact details", previousValue: "0917xxxxxxx", newValue: "0918xxxxxxx", createdAt: addDays(TODAY, -20) },
  { id: "al-2", userId: srAcctgPayroll.id, userName: "Wendie Halog", module: "Payroll", action: "lock", description: "Locked payroll period 2026-07-01 to 2026-07-15", previousValue: "open", newValue: "locked", createdAt: addDays(TODAY, -2) },
  { id: "al-3", userId: hrManager.id, userName: "Sheena Evangelista", module: "Leave Management", action: "approve", description: "Approved Vacation Leave request", previousValue: "pending", newValue: "approved", createdAt: addDays(TODAY, -6) },
  { id: "al-4", userId: hrManager.id, userName: "Sheena Evangelista", module: "System Administration", action: "create", description: "Added new work schedule: Flexi", previousValue: null, newValue: "Flexi 09:00-18:00", createdAt: addDays(TODAY, -30) },
  { id: "al-5", userId: hrManager.id, userName: "Sheena Evangelista", module: "Discipline", action: "create", description: "Issued written warning", previousValue: null, newValue: "written_warning", createdAt: addDays(TODAY, -14) },
  { id: "al-6", userId: opsManagerCbt.id, userName: "Marlyn Leonardo", module: "Overtime", action: "approve", description: "Approved 3 OT hours", previousValue: "pending", newValue: "approved (3 hrs)", createdAt: addDays(TODAY, -4) },
  { id: "al-7", userId: srAcctgPayroll.id, userName: "Wendie Halog", module: "Payslips", action: "generate", description: "Generated payslips for 68 employees", previousValue: null, newValue: "68 payslips", createdAt: addDays(TODAY, -16) },
  { id: "al-8", userId: srAcctgPayroll.id, userName: "Wendie Halog", module: "Payroll Reports", action: "generate", description: "Generated monthly employer payroll expense report for June 2026", previousValue: null, newValue: "report generated", createdAt: addDays(TODAY, -1) },
];

// --- Announcements -----------------------------------------------------------
export const ANNOUNCEMENTS: Announcement[] = [
  { id: "an-1", title: "Mid-Year Performance Evaluations Now Open", body: "Department heads may begin conducting Semi-Annual 2026 evaluations for their direct reports. Deadline for submission is July 31.", category: "memo", postedBy: "Sheena Evangelista", postedAt: addDays(TODAY, -3), expiresAt: addDays(TODAY, 20) },
  { id: "an-2", title: "Ninoy Aquino Day — August 21 (Special Non-Working)", body: "Please plan attendance encoding and payroll cut-offs around the August 21 special non-working holiday.", category: "holiday", postedBy: "Sheena Evangelista", postedAt: addDays(TODAY, -1), expiresAt: "2026-08-22" },
  { id: "an-3", title: "Company Town Hall — August 5", body: "All branches are invited to join the Q2 town hall via video conference. Details to follow from your branch manager.", category: "event", postedBy: "Sheilah A. Magdadaro", postedAt: addDays(TODAY, -5), expiresAt: "2026-08-06" },
  { id: "an-4", title: "Updated Leave Filing Policy", body: "Leave requests must now be filed at least 3 working days in advance except for emergency and sick leave.", category: "policy", postedBy: "Sheena Evangelista", postedAt: addDays(TODAY, -10), expiresAt: null },
  { id: "an-5", title: "Welcome New Hires — July 2026", body: "Join us in welcoming our newest team members across Marketing and HR this month!", category: "announcement", postedBy: "Sheena Evangelista", postedAt: addDays(TODAY, -2), expiresAt: addDays(TODAY, 30) },
];
